# Enable RBAC and securityContext best practices
rbac:
  create: true

securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000

grafana:
  enabled: true
  service:
    type: LoadBalancer
    port: 80
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folder: /tmp/dashboards
    datasources:
      enabled: true
  defaultDashboardsEnabled: true

  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    additionalScrapeConfigs: []

alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  enabled: true
  tls:
    enabled: false

# Network policy example
networkPolicy:
  enabled: true
