apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: rayda-app
  name: rayda-hpa
  labels:
    app: rayda-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rayda-app-deployment
  minReplicas: 1  
  maxReplicas: 3   
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50