apiVersion: v1
kind: Service
metadata:
  name: rayda-lb
  namespace: rayda-app
spec:
  selector:
    app: rayda-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer