name: Production Deployment

on:
  push:
    branches:
      - master

concurrency:
  group: prod/${{ github.worflow }}
  cancel-in-progress: true

jobs:
  docker-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: vickysomtee
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push Image  🐳
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/vickysomtee/rayda:${{ github.event.pull_request.head.sha }}   

